# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c8SjHbfUcczKQbt2vcqFrWahGPmBWPck
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import pydotplus  # Check the references if you need help to install this module.
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, export_graphviz  # References: download link and instructions to install Graphviz.
from IPython.display import Image  # To plot decision tree.
from six import StringIO
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor

# %matplotlib inline

df = pd.read_csv('Carseats.csv')

df.head()

df = pd.get_dummies(df)

df.head()

def print_tree(estimator, features, class_names=None, filled=True):
    tree = estimator
    names = features
    color = filled
    classn = class_names

    dot_data = StringIO()
    export_graphviz(estimator, out_file=dot_data, feature_names=features, class_names=classn, filled=filled)
    graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
    return(graph)

# Split data into training and test set
X = df.loc[:, df.columns[1:]]
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=1)

# Fit regression tree
rgr = DecisionTreeRegressor(max_depth=3)  # We could have chosen another max_depth value.
rgr.fit(X_train, y_train)

# Plot the tree
graph = print_tree(rgr, features=list(X_train.columns.values))
Image(graph.create_png())

# Test MSE
print('Test MSE: ', mean_squared_error(y_test, rgr.predict(X_test)))

# Build a regressor
rgr = DecisionTreeRegressor(random_state=1)

# Grid of parameters to hypertune
param_grid = {'max_depth':[1,2,3,4,5,6,7,8,9,10]}

# Run grid search
grid_search = GridSearchCV(rgr,
                           param_grid=param_grid,
                           cv=5)
grid_search.fit(X_train, y_train)

estimator = DecisionTreeRegressor(
    criterion='mse',
    max_depth=None,
    max_features=None,
    max_leaf_nodes=None,
    min_impurity_decrease=1e-07,
    min_samples_leaf=1,
    min_samples_split=2,
    min_weight_fraction_leaf=0.0,
    random_state=1,
    splitter='best'
)

# Set up GridSearchCV
grid_search = GridSearchCV(
    estimator=estimator,
    param_grid={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
    cv=5,
    error_score='raise',
    n_jobs=1,
    return_train_score=True,
    verbose=0
)

#grid_search.best_estimator_

import numpy as np
import pandas as pd
import patsy as pt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from IPython.display import HTML
from ipywidgets import interact
import ipywidgets as widgets
import copy
import warnings
warnings.filterwarnings('ignore')

from sklearn import tree
import graphviz
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Lasso
import statsmodels.api as sm
from sklearn.neighbors import KNeighborsClassifier

carseats_df = pd.read_csv('Carseats.csv')

# Check for missing values
assert carseats_df.isnull().sum().sum() == 0
# Drop unused index
#carseats_df = carseats_df.drop('Unnamed: 0', axis=1)

# Create index for training set
np.random.seed(1)
train = np.random.random(len(carseats_df)) > 0.5

display(carseats_df.head())

# Use all features excpet response features
# No intercept

preds = carseats_df.columns.drop(['Sales'])
#preds_scaled = ['standardize({})'.format(p) for p in preds]
f = 'Sales ~ 0 +' + ' + '.join(preds)
y, X = pt.dmatrices(f, carseats_df)
y = y.flatten()

# Fit Sklearn's tree regressor
clf = tree.DecisionTreeRegressor(max_depth=5).fit(X[train], y[train])

# Measure test set MSE
y_hat = clf.predict(X[~train])
mse = metrics.mean_squared_error(y[~train], y_hat)

# Get proportion of correct classifications on test set
print('Test MSE: {}'.format(np.around(mse, 3)))
print('Test RMSE: {}'.format(np.around(np.sqrt(mse), 3)))

# How about using CV to compare trees with different number of leaf nodes
# as defined by the max_leaf_nodes parameter?

cv_folds = 10
tuning_param = 'max_leaf_nodes'
columns=[tuning_param, 'RMSE', 'upper', 'lower']

results = []
rmse_array = []
for m in np.arange(2, 100):
    regr = tree.DecisionTreeRegressor(max_leaf_nodes=m)
    scores = cross_val_score(regr, X[train], y[train], cv=cv_folds, scoring='neg_mean_squared_error')
    rmses = np.sqrt(np.absolute(scores))
    rmse = np.mean(rmses)
    conf_int = np.std(rmses) *2
    rmse_array.append(rmse)
    results += [[m, rmse, rmse+conf_int, rmse-conf_int]]

# Plot classification accuracy for each max_depth cv result
plot_df = pd.DataFrame(np.asarray(results), columns=columns).set_index(tuning_param)
plt.figure(figsize=(10,10))
sns.lineplot(data=plot_df)
plt.ylabel('RMSE')
plt.show();

# Show chosen model
chosen = plot_df[plot_df['RMSE'] == plot_df['RMSE'].min()]
display(chosen)

# Use chosen model for test prediction
regr  = tree.DecisionTreeRegressor(max_leaf_nodes=int(chosen.index[0])).fit(X[train], y[train])
y_hat = regr.predict(X[~train])
mse = metrics.mean_squared_error(y[~train], y_hat)

# Get proportion of correct classifications on test set
print('Test MSE : {}'.format(np.around(mse, 3)))
print('Test RMSE: {}'.format(np.around(np.sqrt(mse), 3)))

# Bagging with 100 trees
# although I'm using RandomForestRegressor algo here this is Bagging because max_features = n_predictors

max_features = X.shape[1]
tree_count   = 100

regr   = RandomForestRegressor(max_features=max_features, random_state=0, n_estimators=tree_count)
regr.fit(X[train], y[train])
y_hat = regr.predict(X[~train])

mse = metrics.mean_squared_error(y[~train], y_hat)
rmse = np.sqrt(mse)

print('Test MSE : {}'.format(np.around(mse, 3)))
print('Test RMSE: {}'.format(np.around(rmse, 3)))

# Plot feature by importance in this model
plot_df = pd.DataFrame({'feature': X.design_info.column_names, 'importance': regr.feature_importances_})

plt.figure(figsize=(10,10))
sns.barplot(x='importance', y='feature', data=plot_df.sort_values('importance', ascending=False),
            color='g')
plt.xticks(rotation=90);

# Random Forest with 100 trees and 4 features considered at each split

max_features = 7
tree_count   = 100

regr   = RandomForestRegressor(max_features=max_features, random_state=0, n_estimators=tree_count)
regr.fit(X[train], y[train])
y_hat = regr.predict(X[~train])

mse = metrics.mean_squared_error(y[~train], y_hat)
rmse = np.sqrt(mse)

print('MSE test: {}'.format(np.around(mse, 3)))
print('RMSE test: {}'.format(np.around(rmse, 3)))

# Plot feature by importance in this model
plot_df = pd.DataFrame({'feature': X.design_info.column_names, 'importance': regr.feature_importances_})

plt.figure(figsize=(10,10))
sns.barplot(x='importance', y='feature', data=plot_df.sort_values('importance', ascending=False),
            color='g')
plt.xticks(rotation=90);

# Describe the effect of m, the number of variables considered at each split, on the error rate obtained.

results = []
for max_features in np.arange(1, X.shape[1]):

    tree_count   = 100

    regr   = RandomForestRegressor(max_features=max_features, random_state=0, n_estimators=tree_count)
    regr.fit(X[train], y[train])
    y_hat = regr.predict(X[~train])

    mse = metrics.mean_squared_error(y[~train], y_hat)
    rmse = np.sqrt(mse)

    results += [[max_features, mse]]

plt.figure(figsize=(10,5))
sns.lineplot(x='Split Variables', y='MSE', data=pd.DataFrame(results, columns=['Split Variables', 'MSE']));

########################## PROBLEM 8.11 #####################################

caravan_df = pd.read_csv('Caravan.csv')

# Patsy feature processing
f = 'C(Purchase) ~ ' + ' + '.join(caravan_df.columns.drop(['Purchase']))
y, X = pt.dmatrices(f, caravan_df)
y = y[:, 1]

# Display processed features
display(pd.DataFrame(X, columns=X.design_info.column_names).head())

# Index for Training set of 1000
np.random.seed(1)
train_sample = np.random.choice(np.arange(len(caravan_df)), size=1000, replace=False)
train = np.asarray([(i in train_sample) for i in caravan_df.index])

max_features = 'auto'
tree_count   = 1000
learning_rate = 0.01

model = GradientBoostingClassifier(max_features=max_features,
                                       random_state=1,
                                       n_estimators=tree_count,
                                       learning_rate=learning_rate)

model = model.fit(X[train], y[train])
#y_hat_test  = regr.predict(X[~train])

accuracy = model.score(X[~train], y[~train])
print('accuracy: {}%'.format(np.around(accuracy*100, 2)))

# Plot feature by importance in this model

plot_df = pd.DataFrame({'feature': X.design_info.column_names, 'importance': model.feature_importances_})

plt.figure(figsize=(10,20))
sns.barplot(x='importance', y='feature', data=plot_df.sort_values('importance', ascending=False),
            color='g')
plt.xticks(rotation=90);

max_features = 'auto'
tree_count   = 1000
learning_rate = 0.01

model = GradientBoostingClassifier(max_features=max_features,
                                       random_state=1,
                                       n_estimators=tree_count,
                                       learning_rate=learning_rate)

model = model.fit(X[train], y[train])
#y_hat_test  = regr.predict(X[~train])


# Boosting stats
threshold = 0.2
y_hat_proba = model.predict_proba(X[~train])
y_hat = (y_hat_proba[:, 1] > threshold).astype(np.float64)
confusion_mat = confusion_matrix(y[~train], y_hat)

# What fraction of the people predicted to make a purchase do in fact make one?
pos_pred_val = np.around(confusion_mat[:, 1][1] / np.sum(confusion_mat[:, 1]), 5)

display(HTML('<h4>BOOSTING: Confusion matrix</h4>'))
print(confusion_mat)

print('\nPositive Predictive Value: {}'.format(pos_pred_val))

# KNN

# PREDICT
for K in range(1, 10):
    # model
    model = KNeighborsClassifier(n_neighbors=K).fit(X[train], y[train])
    # Predict
    y_pred = model.predict(X[~train])

    # Confusion table
    display(HTML('<h3>K={}</h3>'.format(K)))
    confusion_mtx = confusion_matrix(y[~train], y_pred)
    print(confusion_mtx)

    ## Classifier stats
    pos_pred_val = np.around(confusion_mtx[:, 1][1] / np.sum(confusion_mtx[:, 1]), 5)
    print('\nPositive Predictive Value: {}'.format(pos_pred_val))

!pip install lifelines

from lifelines import KaplanMeierFitter, CoxPHFitter
from lifelines.statistics import logrank_test
import pandas as pd
import matplotlib.pyplot as plt

# Data from Table 11.4
data = {
    "Observation": [26.5, 37.2, 57.3, 90.8, 20.2, 89.8],
    "Censoring_Indicator": [1, 1, 1, 0, 0, 0],
    "Covariate": [0.1, 11, -0.3, 2.8, 1.8, 0.4]
}

df = pd.DataFrame(data)

# Grouping based on the covariate X
df['Group'] = df['Covariate'].apply(lambda x: 1 if x < 2 else 2)

# Kaplan-Meier survival curves
kmf = KaplanMeierFitter()

ax = plt.subplot(111)

for group in df['Group'].unique():
    group_data = df[df['Group'] == group]
    kmf.fit(group_data['Observation'], event_observed=group_data['Censoring_Indicator'], label=f'Group {group}')
    kmf.plot_survival_function(ax=ax)

plt.title('Kaplan-Meier Survival Curves')
plt.xlabel('Time')
plt.ylabel('Survival Probability')
plt.show()

import pandas as pd
from lifelines import KaplanMeierFitter, CoxPHFitter
from lifelines.statistics import logrank_test
import matplotlib.pyplot as plt

# Assuming the data is in a DataFrame with the specified columns
data = {
    "Observation": [26.5, 37.2, 57.3, 90.8, 20.2, 89.8],
    "Censoring_Indicator": [1, 1, 1, 0, 0, 0],
    "Covariate": [0.1, 11, -0.3, 2.8, 1.8, 0.4]
}
df = pd.DataFrame(data)

# Define the groups based on the covariate
df['Group'] = (df['Covariate'] >= 2).astype(int)

# Kaplan-Meier survival curves
kmf = KaplanMeierFitter()

# Plot for Group 1
ax = plt.subplot(111)
mask = df['Group'] == 0
kmf.fit(df[mask]['Observation'], event_observed=df[mask]['Censoring_Indicator'], label='Group 1')
kmf.plot_survival_function(ax=ax)

# Plot for Group 2
mask = df['Group'] == 1
kmf.fit(df[mask]['Observation'], event_observed=df[mask]['Censoring_Indicator'], label='Group 2')
kmf.plot_survival_function(ax=ax)

plt.title('Kaplan-Meier Survival Curves')
plt.xlabel('Time')
plt.ylabel('Survival probability')
plt.show()

# Cox's proportional hazards model
cph = CoxPHFitter()
df['Group'] = df['Group'].astype('category')  # Convert to categorical for the Cox model
cph.fit(df, 'Observation', event_col='Censoring_Indicator', formula="Group")
cph.print_summary()  # This will print the summary of the Cox model

# Log-rank test
group1 = df[df['Group'] == 0]
group2 = df[df['Group'] == 1]
results = logrank_test(group1['Observation'], group2['Observation'], event_observed_A=group1['Censoring_Indicator'], event_observed_B=group2['Censoring_Indicator'])
print('Log-rank test p-value:', results.p_value)

