# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CK2lmnDVDs8kNMdaGfQyXFAjfHDXJYCw
"""

import pandas as pd
import matplotlib.pyplot as plt


college = pd.read_csv("/home/College.csv")

college

college2 = pd.read_csv('/home/College.csv', index_col=0)
college3 = college.rename({'Unnamed: 0': 'College'},axis=1)
college3 = college3.set_index('College')

college
college2
college3

college = college3

college.describe()

pd.plotting.scatter_matrix(college[['Top10perc', 'Apps', 'Enroll']])

college.boxplot(column='Outstate', by='Private')

college['Elite'] = pd.cut(college['Top10perc'], [0,50,100], labels=['No', 'Yes'])
college['Elite']
college['Elite'].value_counts()

college.boxplot(column='Outstate', by='Elite')
plt.title('Outstate vs Elite')

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
college['Apps'].plot.hist(ax=axes[0, 0], bins=20)
college['Enroll'].plot.hist(ax=axes[0, 1], bins=20)
college['F.Undergrad'].plot.hist(ax=axes[1, 0], bins=20)
college['Expend'].plot.hist(ax=axes[1, 1], bins=20)
plt.show()

# Calculate mean, median, and mode for each variable
mean_values = college[['Apps', 'Enroll', 'F.Undergrad', 'Expend']].mean()
median_values = college[['Apps', 'Enroll', 'F.Undergrad', 'Expend']].median()
mode_values = college[['Apps', 'Enroll', 'F.Undergrad', 'Expend']].mode().iloc[0]

# Create a DataFrame to display the results
summary_df = pd.DataFrame({'Mean': mean_values, 'Median': median_values, 'Mode': mode_values})
summary_df

########################## PROBLEM 9 ##############################
import numpy as np
import seaborn as sns


auto = pd.read_csv('/home/Auto.csv')

auto = auto.dropna()

quantitative_predictors = auto.select_dtypes(include=[np.number]).columns.tolist()
qualitative_predictors = auto.select_dtypes(exclude=[np.number]).columns.tolist()

print("Quantitative Predictors:", quantitative_predictors)
print("Qualitative Predictors:", qualitative_predictors)

range_values = auto[quantitative_predictors].agg([np.min, np.max])
print("\nRange of Quantitative Predictors:")
print(range_values)

mean_std_values = auto[quantitative_predictors].agg([np.mean, np.std])
print("\nMean and Standard Deviation of Quantitative Predictors:")
print(mean_std_values)

auto_subset = auto.drop(auto.index[9:85])

range_values_subset = auto_subset[quantitative_predictors].agg([np.min, np.max])
mean_std_values_subset = auto_subset[quantitative_predictors].agg([np.mean, np.std])

print("\nRange of Quantitative Predictors (Subset):")
print(range_values_subset)
print("\nMean and Standard Deviation of Quantitative Predictors (Subset):")
print(mean_std_values_subset)

sns.pairplot(auto, vars=quantitative_predictors)

correlation_matrix = auto.corr()
mpg_correlations = correlation_matrix['mpg']
print(mpg_correlations)

# Plot correlations with mpg
plt.figure(figsize=(10, 5))
mpg_correlations.plot(kind='bar', title='Correlations with MPG')
plt.ylabel('Correlation')
plt.xlabel('Predictor')
plt.show()

################# Problem 13 ################
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

np.random.seed(1)
x = np.random.normal(0, 1, 100)

eps = np.random.normal(0, 0.1, 100)

y = -1 + 0.5 * x + eps

# eps_less_noise = np.random.normal(0, 0.1, 100)  # Smaller variance (e.g., 0.1)
# y_less_noise = -1 + 0.5 * x + eps_less_noise

# eps_more_noise = np.random.normal(0, 0.5, 100)  # Larger variance (e.g., 0.5)
# y_more_noise = -1 + 0.5 * x + eps_more_noise

print(len(y))

beta0 = -1
beta1 = 0.5

model = LinearRegression()
model.fit(x.reshape(-1, 1), y)
beta0_hat = model.intercept_
beta1_hat = model.coef_[0]

# Print the calculated and estimated coefficients
print(f'0 (Actual): {beta0:.4f}')
print(f'1 (Actual): {beta1:.4f}')
print(f'0hat (Estimated): {beta0_hat:.4f}')
print(f'1hat (Estimated): {beta1_hat:.4f}')

plt.scatter(x, y, label='Data')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Scatterplot of x vs. y')
plt.legend()
plt.show()

model = LinearRegression()
model.fit(x.reshape(-1, 1), y)
beta0_hat = model.intercept_
beta1_hat = model.coef_[0]
print(f'β̂₀ (intercept): {beta0_hat}')
print(f'β̂₁ (slope): {beta1_hat}')

plt.scatter(x, y, label='Data')
plt.plot(x, model.predict(x.reshape(-1, 1)), color='red', label='Least Squares Line')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Scatterplot with Least Squares Line')
plt.legend()
plt.show()

poly_features = PolynomialFeatures(degree=2)
x_poly = poly_features.fit_transform(x.reshape(-1, 1))
model_poly = LinearRegression()
model_poly.fit(x_poly, y)

from sklearn.metrics import r2_score


# Linear Model
y_pred_linear = model.predict(x.reshape(-1, 1))
r2_linear = r2_score(y, y_pred_linear)
print(f'R-squared (Linear Model): {r2_linear:.4f}')

# Polynomial (Quadratic) Model
y_pred_poly = model_poly.predict(x_poly)
r2_poly = r2_score(y, y_pred_poly)
print(f'R-squared (Polynomial Model): {r2_poly:.4f}')

import statsmodels.api as sm

# Define a function to calculate confidence intervals
def calculate_confidence_intervals(x, y):
    x_with_const = sm.add_constant(x)

    model = sm.OLS(y, x_with_const).fit()

    confidence_intervals = model.conf_int(alpha=0.05)  # 95% confidence intervals

    return confidence_intervals

conf_intervals_original = calculate_confidence_intervals(x, y)

eps_noisier = np.random.normal(0, 0.5, 100)  # Increase variance for more noise
y_noisier = -1 + 0.5 * x + eps_noisier
conf_intervals_noisier = calculate_confidence_intervals(x, y_noisier)

eps_less_noisy = np.random.normal(0, 0.1, 100)  # Decrease variance for less noise
y_less_noisy = -1 + 0.5 * x + eps_less_noisy
conf_intervals_less_noisy = calculate_confidence_intervals(x, y_less_noisy)

print("Confidence Intervals (Original Data):")
print(conf_intervals_original)

print("\nConfidence Intervals (Noisier Data):")
print(conf_intervals_noisier)

print("\nConfidence Intervals (Less Noisy Data):")
print(conf_intervals_less_noisy)

############################ PROBLEM 14 #####################

rng = np.random.default_rng(10)
x1 = rng.uniform(0, 1, size=100)
x2 = 0.5 * x1 + rng.normal(size=100) / 10
y = 2 + 2 * x1 + 0.3 * x2 + rng.normal(size=100)

import matplotlib.pyplot as plt

correlation = np.corrcoef(x1, x2)[0, 1]
print("Correlation between x1 and x2:", correlation)

plt.scatter(x1, x2)
plt.xlabel('x1')
plt.ylabel('x2')
plt.title('Scatterplot of x1 vs. x2')
plt.show()

import statsmodels.api as sm

X = sm.add_constant(np.column_stack((x1, x2)))
model = sm.OLS(y, X).fit()
coefficients = model.params
print("βˆ0:", coefficients[0])
print("βˆ1:", coefficients[1])
print("βˆ2:", coefficients[2])

# Testing null hypotheses
p_value_beta1 = model.pvalues[1]
p_value_beta2 = model.pvalues[2]
print("p-value for H0: β1 = 0:", p_value_beta1)
print("p-value for H0: β2 = 0:", p_value_beta2)

X1_only = sm.add_constant(x1)
model_x1_only = sm.OLS(y, X1_only).fit()
p_value_x1 = model_x1_only.pvalues[1]
print("βˆ0 (x1 only):", model_x1_only.params[0])
print("βˆ1 (x1 only):", model_x1_only.params[1])
print("p-value for H0: β1 (x1 only) = 0:", p_value_x1)

X2_only = sm.add_constant(x2)
model_x2_only = sm.OLS(y, X2_only).fit()
p_value_x2 = model_x2_only.pvalues[1]
print("βˆ0 (x2 only):", model_x2_only.params[0])
print("βˆ1 (x2 only):", model_x2_only.params[1])
print("p-value for H0: β1 (x2 only) = 0:", p_value_x2)

# Original data
rng = np.random.default_rng(10)
x1 = rng.uniform(0, 1, size=100)
x2 = 0.5 * x1 + rng.normal(size=100) / 10
y = 2 + 2 * x1 + 0.3 * x2 + rng.normal(size=100)

# Fit the original model (c)
X = sm.add_constant(np.column_stack((x1, x2)))
model = sm.OLS(y, X).fit()

# New data
x1_new = np.concatenate([x1, [0.1]])
x2_new = np.concatenate([x2, [0.8]])
y_new = np.concatenate([y, [6]])

# Fit the models again with the new data
X_new = sm.add_constant(np.column_stack((x1_new, x2_new)))
model_new = sm.OLS(y_new, X_new).fit()

# Check for outliers and high-leverage points
outlier_status = model_new.outlier_test()
high_leverage_status = model_new.get_influence().hat_matrix_diag

print("Outlier status for the new observation:", outlier_status[-1])
print("High-leverage status for the new observation:", high_leverage_status[-1])