# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KS-dQPzllcB46K9KLWQCUyFkBeXRfVw1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Auto dataset
auto = pd.read_csv('/home/Auto.csv')

# (a) Create the binary variable mpg01
median_mpg = auto['mpg'].median()
auto['mpg01'] = np.where(auto['mpg'] > median_mpg, 1, 0)

# Compute the correlation matrix
corr_matrix = auto.corr()

# Create a heatmap of the correlation matrix
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

quantitative_predictors = auto.select_dtypes(include=[np.number]).columns.tolist()
qualitative_predictors = auto.select_dtypes(exclude=[np.number]).columns.tolist()

print("Quantitative Predictors:", quantitative_predictors)
print("Qualitative Predictors:", qualitative_predictors)

sns.pairplot(auto, vars=quantitative_predictors)

from sklearn.model_selection import train_test_split

X = auto.drop(['mpg01'], axis=1)
y = auto['mpg01']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(X_train[['cylinders', 'weight', 'displacement']], y_train)
test_error_lda = 1 - lda.score(X_test[['cylinders', 'weight', 'displacement']], y_test)
print("Test error of LDA:", test_error_lda)

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train[['cylinders', 'weight', 'displacement']], y_train)
test_error_qda = 1 - qda.score(X_test[['cylinders', 'weight', 'displacement']], y_test)
print("Test error of QDA:", test_error_qda)

from sklearn.linear_model import LogisticRegression

logistic_reg = LogisticRegression()
logistic_reg.fit(X_train[['cylinders', 'weight', 'displacement']], y_train)
test_error_logistic = 1 - logistic_reg.score(X_test[['cylinders', 'weight', 'displacement']], y_test)
print("Test error of Logistic Regression:", test_error_logistic)

from sklearn.naive_bayes import GaussianNB

naive_bayes = GaussianNB()
naive_bayes.fit(X_train[['cylinders', 'weight', 'displacement']], y_train)
test_error_nb = 1 - naive_bayes.score(X_test[['cylinders', 'weight', 'displacement']], y_test)
print("Test error of Naive Bayes:", test_error_nb)

from sklearn.neighbors import KNeighborsClassifier

# Example loop to test different values of K
best_k = None
best_test_error_knn = float('inf')

for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train[['cylinders', 'weight', 'displacement']], y_train)
    test_error_knn = 1 - knn.score(X_test[['cylinders', 'weight', 'displacement']], y_test)
    print("K: ", k)
    print("Error: ", test_error_knn)
    if test_error_knn < best_test_error_knn:
        best_test_error_knn = test_error_knn
        best_k = k

print("Best K for KNN:", best_k)
print("Test error of KNN with best K:", best_test_error_knn)

############ PROBLEM 5.5 ###############

import pandas as pd
import statsmodels.api as sm
import numpy as np


default_data = pd.read_csv("/home/Default.csv")

# Set seed for reproducibility
np.random.seed(42)

# Convert 'default' column to 0 and 1
default_data['default'] = default_data['default'].map({'No': 0, 'Yes': 1})
default_data['student'] = default_data['student'].map({'No': 0, 'Yes': 1})

for i in range(3):
  # Create a random sample for training
  train = np.random.choice(default_data.index, size=int(len(default_data) / 2), replace=False)

  # Split the data into training and validation sets
  train_data = default_data.loc[train]
  validation_data = default_data.drop(train)

  # Create and fit the logistic regression model on the training data
  model = sm.GLM(
      train_data['default'],  # Dependent variable for training
      train_data[['income', 'balance']],  # Independent variables for training
      family=sm.families.Binomial()
  )
  fit = model.fit()


  # Make predictions on the validation set
  pred_probs = fit.predict(validation_data[['income', 'balance']])
  pred = np.where(pred_probs > 0.5, 1, 0)


  # Convert 'actual_values' to integers
  actual_values = validation_data['default'].astype(int)

  # Create a table of predicted vs. actual values for the validation set
  result_table = pd.crosstab(pred, actual_values)

  print(result_table)

  # Compute the validation set error
  validation_error = np.mean(pred != actual_values)
  print("Validation Set Error:", validation_error)

for i in range(3):
  # Create a random sample for training
  train = np.random.choice(default_data.index, size=int(len(default_data) / 2), replace=False)

  # Split the data into training and validation sets
  train_data = default_data.loc[train]
  validation_data = default_data.drop(train)

  # Create and fit the logistic regression model on the training data
  model = sm.GLM(
      train_data['default'],  # Dependent variable for training
      train_data[['income', 'balance', 'student']],  # Independent variables for training
      family=sm.families.Binomial()
  )
  fit = model.fit()

  # Make predictions on the validation set
  pred_probs = fit.predict(validation_data[['income', 'balance', 'student']])
  pred = np.where(pred_probs > 0.5, 1, 0)


  # Convert 'actual_values' to integers
  actual_values = validation_data['default'].astype(int)

  # Create a table of predicted vs. actual values for the validation set
  result_table = pd.crosstab(pred, actual_values)

  print(result_table)

  # Compute the validation set error
  validation_error = np.mean(pred != actual_values)
  print("Validation Set Error:", validation_error)

################# PROBLEM 5.6 ##################

import pandas as pd
import statsmodels.api as sm
import numpy as np


default_data = pd.read_csv("/home/Default.csv")

# Set seed for reproducibility
np.random.seed(42)

model = sm.GLM.from_formula("default ~ income + balance", data=default_data, family=sm.families.Binomial()).fit()

# Use the summary() function to get standard errors
summary = model.summary()
standard_errors = model.bse
print(standard_errors)

def boot_fn(data, indices):
    sample_data = data.iloc[indices]  # Select the bootstrapped sample
    model = sm.GLM.from_formula("default ~ income + balance", data=sample_data, family=sm.families.Binomial()).fit()
    return model.params  # Return coefficient estimates

# Set a random seed for reproducibility
np.random.seed(123)

# Bootstrap
n_iterations = 100  # Number of bootstrap iterations
coef_samples = []

for _ in range(n_iterations):
    # Generate random indices with replacement
    boot_indices = np.random.choice(default_data.index, size=len(default_data), replace=True)

    # Call boot_fn() to get coefficients and append them to the list
    coef_samples.append(boot_fn(default_data, boot_indices))

# Calculate standard errors from the coefficient samples
coef_samples_df = pd.DataFrame(coef_samples)
bootstrap_standard_errors = coef_samples_df.std()
print(bootstrap_standard_errors)

############## PROBLEM 5.7 ################

import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
np.random.seed(42)
data = pd.read_csv('/home/Weekly.csv')

print(data.head())

# (a) Fit a logistic regression model that predicts Direction using Lag1 and Lag2.
X_a = data[['Lag1', 'Lag2']]
X_a = sm.add_constant(X_a)  # Add a constant term for intercept
y_a = (data['Direction'] == 'Up').astype(int)

model_a = sm.GLM(y_a, X_a, family=sm.families.Binomial()).fit()

# (b) Fit a logistic regression model that predicts Direction using Lag1 and Lag2 using all but the first observation.
X_b = data.iloc[1:][['Lag1', 'Lag2']]
X_b = sm.add_constant(X_b)
y_b = (data.iloc[1:]['Direction'] == 'Up').astype(int)

model_b = sm.GLM(y_b, X_b, family=sm.families.Binomial()).fit()

# (c) Use the model from (b) to predict the direction of the first observation.
X_c = data.iloc[0][['Lag1', 'Lag2']]
X_c = sm.add_constant(X_c)
y_c_actual = (data.iloc[0]['Direction'] == 'Up')
y_c_pred = (model_b.predict(X_a.iloc[0].values.reshape(1, -1)) > 0.5)[0]
print(y_c_actual)
print(y_c_pred)
correct_c = (y_c_pred == y_c_actual)
print(f"Is observation correctly classified? : {correct_c}")

# (d) LOOCV - Leave-One-Out Cross Validation
n = len(data)
error = np.zeros(n)

for i in range(n):
    X_d_train = data.drop(index=i)[['Lag1', 'Lag2']]
    X_d_train = sm.add_constant(X_d_train)
    y_d_train = (data.drop(index=i)['Direction'] == 'Up')

    model_d = sm.GLM(y_d_train, X_d_train, family=sm.families.Binomial()).fit()

    X_d_test = data[['Lag1', 'Lag2']]
    X_d_test = sm.add_constant(X_d_test)
    X_d_test = X_d_test.iloc[i].values.reshape(1, -1)
    y_d_test_actual = (data.iloc[i]['Direction'] == 'Up')

    y_d_pred = (model_d.predict(X_d_test) > 0.5).astype(int)[0]
    error[i] = int(y_d_pred != y_d_test_actual)

# (e) Calculate the LOOCV estimate for the test error and comment on the results.
loocv_error = error.mean()
print(f"LOOCV Estimate for Test Error: {loocv_error}")