# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rkp-uCOkjFOKYblS3TNa9xd7XVsesFu0
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
!pip install pygam
from pygam import LinearGAM

# %matplotlib inline

df = pd.read_csv('College.csv', index_col=0)

df.head()

df = pd.get_dummies(df)

df.head()

X = df.loc[:, df.columns != 'Outstate']
y = df['Outstate']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=1)

lr = LinearRegression()

sfs = SFS(lr,
          k_features = 18,  # We have 18 features
          forward = True,
          floating = False,
          scoring = 'r2',
          cv = 0)

sfs = sfs.fit(X_train.values, y_train)  # to be readable by sfs

fig = plot_sfs(sfs.get_metric_dict())

#plt.title('Sequential forward selection (w. StdDev)')
plt.title('Sequential forward selection')
plt.grid()
plt.show()

pd.DataFrame.from_dict(sfs.get_metric_dict()).T

print('Variables: %s, %s, %s, %s, %s, %s' % (X.columns[16], X.columns[7], X.columns[10], X.columns[13], X.columns[14], X.columns[15]))

selected_predictors = [X.columns[16], X.columns[7], X.columns[10], X.columns[13], X.columns[14], X.columns[15]]
gam = LinearGAM().fit(X_train[selected_predictors].values, y_train)



plt.figure(figsize=(35, 20))  # Adjust the figure size as needed for two rows

for i, term in enumerate(gam.terms):
    if term.isintercept:
        continue
    XX = gam.generate_X_grid(term=i)
    pdep, confi = gam.partial_dependence(term=i, X=XX, width=0.95)

    # Create subplots with two rows
    plt.subplot(2, 3, i + 1)  # 2 rows, 3 columns
    plt.plot(XX[:, term.feature], pdep)
    plt.title(selected_predictors[i])

plt.tight_layout()  # Adjust subplot layout
plt.show()

y_pred = gam.predict(X_test[selected_predictors])

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared (R2):", r2)

print(gam.summary())

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn import preprocessing

df = pd.read_csv('College.csv')#, index_col=0)

df.info()

df.head()

df.describe()

X = df.iloc[:,3:]
X = X.iloc[:,:-1]

X.head()

y = df['Apps']

y.head()

X_train,  X_test,  y_train,  y_test  =  train_test_split(X, y, random_state=0)

lr = LinearRegression()
lr.fit(X_train, y_train)

np.mean((lr.predict(X_test) - y_test) ** 2)

lr.score(X_test, y_test)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

rcv = RidgeCV(alphas=np.linspace(.01, 100, 1000),  cv=10)

rcv.fit(X_train_scaled, y_train)

rcv.score(X_test_scaled,y_test)

np.mean((rcv.predict(scaler.transform(X_test)) - y_test) ** 2)

lcv = LassoCV(alphas=np.linspace(.01, 100, 1000),  cv=10)

lcv.fit(X_train_scaled, y_train)

np.mean((lcv.predict(scaler.transform(X_test)) - y_test) ** 2)

lcv.score(X_test_scaled,y_test)

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from itertools import combinations
from sklearn.metrics import mean_squared_error

# Setting the random seed
np.random.seed(42)

# a. Generating the data
p = 15
n = 1000
dat = np.random.randn(n, p)
beta = np.zeros(p)
beta[0:4] = [5, 4, 2, 7]
y = np.dot(dat, beta) + np.random.randn(n)
dat = pd.DataFrame(dat, columns=[f'b{i+1}' for i in range(p)])
dat['y'] = y

# b. Splitting the data
train = dat.iloc[0:100]
test = dat.iloc[100:1000]

# c. Best subset selection
def fit_best_subset(X, y, k):
    models = list(combinations(X.columns, k))
    best_mse = float('inf')
    best_model = None

    for model in models:
        lm = LinearRegression().fit(X[list(model)], y)
        mse = mean_squared_error(y, lm.predict(X[list(model)]))
        if mse < best_mse:
            best_mse = mse
            best_model = model

    return best_model

train_mse = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    mse = mean_squared_error(train['y'], lm.predict(train[list(model)]))
    train_mse.append(mse)

# Plotting the training MSE
import matplotlib.pyplot as plt
plt.plot(range(1, p + 1), train_mse, marker='o')
plt.ylabel("MSE")
plt.xlabel("Model Size")
plt.show()

# d. Testing the models on test set
test_mse = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    mse = mean_squared_error(test['y'], lm.predict(test[list(model)]))
    test_mse.append(mse)

# Plotting the test MSE
plt.plot(range(1, p + 1), test_mse, marker='o', color='r')
plt.ylabel("MSE")
plt.xlabel("Model Size")
plt.show()

# e. Minimum MSE model size
min_mse_model_size = np.argmin(test_mse) + 1
print(f"The min test MSE is found when model size is {min_mse_model_size}.")

# f. Coefficient comparison
best_model = fit_best_subset(train.drop(columns=['y']), train['y'], min_mse_model_size)
lm_best = LinearRegression().fit(train[list(best_model)], train['y'])
coeffs = lm_best.coef_
print("Estimated Coefficients:", coeffs)

# g. Plotting coefficient error
errors = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    est_coeffs = np.zeros(p)
    true_coeffs = beta.copy()
    for idx, col in enumerate(model):
        j = int(col[1:]) - 1
        est_coeffs[j] = lm.coef_[idx]
    errors.append(np.sqrt(np.sum((true_coeffs - est_coeffs)**2)))

plt.plot(range(1, p + 1), errors, marker='o', color='b')
plt.ylabel("Mean squared coefficient error")
plt.xlabel("Model Size")
plt.show()

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from itertools import combinations
from sklearn.metrics import mean_squared_error

# Setting the random seed
np.random.seed(42)

# a. Generating the data
p = 20
n = 1000
dat = np.random.randn(n, p)
beta = np.zeros(p)
beta[0:4] = [5, 4, 2, 7]
y = np.dot(dat, beta) + np.random.randn(n)
dat = pd.DataFrame(dat, columns=[f'b{i+1}' for i in range(p)])
dat['y'] = y

# b. Splitting the data
train = dat.iloc[0:100]
test = dat.iloc[100:1000]

# c. Best subset selection
def fit_best_subset(X, y, k):
    models = list(combinations(X.columns, k))
    best_mse = float('inf')
    best_model = None

    for model in models:
        lm = LinearRegression().fit(X[list(model)], y)
        mse = mean_squared_error(y, lm.predict(X[list(model)]))
        if mse < best_mse:
            best_mse = mse
            best_model = model

    return best_model

train_mse = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    mse = mean_squared_error(train['y'], lm.predict(train[list(model)]))
    train_mse.append(mse)

# Plotting the training MSE
import matplotlib.pyplot as plt
plt.plot(range(1, p + 1), train_mse, marker='o')
plt.ylabel("MSE")
plt.xlabel("Model Size")
plt.show()

# d. Testing the models on test set
test_mse = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    mse = mean_squared_error(test['y'], lm.predict(test[list(model)]))
    test_mse.append(mse)

# Plotting the test MSE
plt.plot(range(1, p + 1), test_mse, marker='o', color='r')
plt.ylabel("MSE")
plt.xlabel("Model Size")
plt.show()

# e. Minimum MSE model size
min_mse_model_size = np.argmin(test_mse) + 1
print(f"The min test MSE is found when model size is {min_mse_model_size}.")

# f. Coefficient comparison
best_model = fit_best_subset(train.drop(columns=['y']), train['y'], min_mse_model_size)
lm_best = LinearRegression().fit(train[list(best_model)], train['y'])
coeffs = lm_best.coef_
print("Estimated Coefficients:", coeffs)

# g. Plotting coefficient error
errors = []
for i in range(1, p + 1):
    model = fit_best_subset(train.drop(columns=['y']), train['y'], i)
    lm = LinearRegression().fit(train[list(model)], train['y'])
    est_coeffs = np.zeros(p)
    true_coeffs = beta.copy()
    for idx, col in enumerate(model):
        j = int(col[1:]) - 1
        est_coeffs[j] = lm.coef_[idx]
    errors.append(np.sqrt(np.sum((true_coeffs - est_coeffs)**2)))

plt.plot(range(1, p + 1), errors, marker='o', color='b')
plt.ylabel("Mean squared coefficient error")
plt.xlabel("Model Size")
plt.show()

import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

np.random.seed(5)

# Generated dataset
X1 = np.random.normal(0, 2, 100)
X2 = np.random.normal(0, np.sqrt(2), 100)
eps = np.random.normal(0, 1, 100)
b0, b1, b2 = 5, 2.5, 11.5
Y = b0 + b1*X1 + b2*X2 + eps

beta1 = 0.1
a = Y - beta1 * X1
X = sm.add_constant(X2)
model = sm.OLS(a, X).fit()
beta0, beta2 = model.params

a = Y - beta2 * X2
X = sm.add_constant(X1)
model = sm.OLS(a, X).fit()
beta0, beta1 = model.params

beta_vals = {'beta0': [], 'beta1': [], 'beta2': []}
beta1 = 0.1

for i in range(1000):
    a = Y - beta1 * X1
    X = sm.add_constant(X2)
    model = sm.OLS(a, X).fit()
    beta2 = model.params[1]
    beta_vals['beta2'].append(beta2)

    a = Y - beta2 * X2
    X = sm.add_constant(X1)
    model = sm.OLS(a, X).fit()
    beta0, beta1 = model.params
    beta_vals['beta0'].append(beta0)
    beta_vals['beta1'].append(beta1)

plt.figure(figsize=(10, 6))
plt.plot(beta_vals['beta0'], color='green', linewidth=3, label='beta0')
plt.plot(beta_vals['beta1'], color='red', linewidth=3, label='beta1')
plt.plot(beta_vals['beta2'], color='blue', linewidth=3, label='beta2')

# Using results from multiple linear regression in part (f)
X = sm.add_constant(np.column_stack((X1, X2)))
model = sm.OLS(Y, X).fit()
b0_lm, b1_lm, b2_lm = model.params

plt.axhline(y=b0_lm, color='black', linestyle='--', linewidth=2)
plt.axhline(y=b1_lm, color='yellow', linestyle='--', linewidth=2)
plt.axhline(y=b2_lm, color='green', linestyle='--', linewidth=2)

plt.xlabel("Iteration")
plt.ylabel("Coefficient value")
plt.title("Coefficients found by iterating, and overlaid values from lm() function.")
plt.legend()
plt.grid(True)
plt.show()

print("Coefficients from multiple linear regression:")
print("Beta0:", b0_lm)
print("Beta1:", b1_lm)
print("Beta2:", b2_lm)